parameters:
#    authenticator_applications_users.example.class: Authenticator\ApplicationsUsersBundle\Example

services:
#    authenticator_applications_users.example:
#        class: %authenticator_applications_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
